-- ═══════════════════════════════════════════════════════════
-- NOMOΣ Phase 5 — Seed Data (Email Templates + Performance)
-- ═══════════════════════════════════════════════════════════

-- Insert all 24 email templates
INSERT INTO email_templates (code, category, objet_template, contenu_template, destinataire_role, variables) VALUES
-- Workflow (8 templates)
('RAPPEL_DEPOT_J5', 'workflow', 'Rappel — Dépôt situation avant le {deadline}', 'Bonjour {entreprise_name},\n\nNous vous rappelons que la date limite de dépôt de votre situation de travaux pour {mois} est le {deadline}.\n\nOpération : {operation_name}\nLot : {lot_name}\n\nMerci de déposer votre situation via NOMOΣ.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,deadline,mois,operation_name,lot_name,moe_name'),
('RELANCE_DEPOT_J3', 'workflow', 'RELANCE — Situation non reçue — {lot_name}', 'Bonjour {entreprise_name},\n\nNous n''avons pas reçu votre situation de travaux.\nDate limite : {deadline} (dans 3 jours).\n\nSans dépôt dans les délais, des pénalités pourront être appliquées conformément au CCAP.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,deadline,lot_name,moe_name'),
('RELANCE_DEPOT_J1', 'workflow', 'DERNIER RAPPEL — Dépôt demain — {lot_name}', 'Bonjour {entreprise_name},\n\n⚠️ DERNIER RAPPEL : votre situation doit être déposée DEMAIN au plus tard.\n\nOpération : {operation_name}\nLot : {lot_name}\nDate limite : {deadline}\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,deadline,operation_name,lot_name,moe_name'),
('CONFIRM_RECEPTION', 'workflow', 'Confirmation — Situation n°{numero} reçue', 'Bonjour {entreprise_name},\n\nNous accusons réception de votre situation de travaux n°{numero}.\n\nOpération : {operation_name}\nLot : {lot_name}\nMontant déclaré : {montant} € HT\nDate de dépôt : {date}\n\nVotre situation va être contrôlée par l''OPC puis le MOE.\n\nCordialement,\nNOMOΣ', 'entreprise', 'entreprise_name,numero,operation_name,lot_name,montant,date'),
('SIGNATURE_REQUISE', 'workflow', 'Certificat n°{numero_certificat} — Signature requise', 'Bonjour {entreprise_name},\n\nLe certificat de paiement n°{numero_certificat} est prêt pour votre signature.\n\nMontant net à payer : {montant} €\n\nConnectez-vous à NOMOΣ pour vérifier et signer le certificat.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,numero_certificat,montant,moe_name'),
('SIGNATURE_CONFIRMEE', 'workflow', 'Signature confirmée — Certificat {numero_certificat}', 'Bonjour,\n\nLa signature du certificat n°{numero_certificat} a été confirmée.\n\nSigné par : {signataire}\nDate : {date}\n\nLe certificat sera transmis au Maître d''Ouvrage.\n\nCordialement,\nNOMOΣ', 'moe', 'numero_certificat,signataire,date'),
('TRANSMISSION_MOA', 'workflow', 'Certificat de paiement — {lot_name} — Situation n°{numero}', 'Monsieur,\n\nVeuillez trouver ci-joint le certificat de paiement pour :\n\nOpération : {operation_name}\nLot : {lot_name}\nEntreprise : {entreprise_name}\nSituation n°{numero}\nMontant net à payer : {montant} €\n\nCordialement,\n{moe_name}', 'moa', 'operation_name,lot_name,entreprise_name,numero,montant,moe_name'),
('AR_CONFIRME', 'workflow', 'AR confirmé — Certificat {numero_certificat}', 'Bonjour {moe_name},\n\nL''accusé de réception du certificat n°{numero_certificat} a été confirmé.\n\nDistribué le : {date}\n\nCordialement,\nNOMOΣ', 'moe', 'moe_name,numero_certificat,date'),

-- Alertes (8 templates)
('CALENDRIER_SPECIAL', 'alerte', 'Calendrier exceptionnel — {motif}', 'Bonjour,\n\nUn calendrier exceptionnel est en vigueur :\n\nMotif : {motif}\nPériode : du {date_debut} au {date_fin}\n\nLes dates limites de dépôt sont ajustées en conséquence.\n\nCordialement,\nNOMOΣ', 'all', 'motif,date_debut,date_fin'),
('CAUTION_EXPIRATION', 'alerte', 'Caution expire le {date} — {entreprise_name}', 'Bonjour {entreprise_name},\n\nVotre caution bancaire arrive à expiration le {date}.\n\n⚠️ Sans renouvellement, une retenue de garantie de 5% sera automatiquement appliquée.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,date,moe_name'),
('ASSURANCE_EXPIREE', 'alerte', 'BLOCAGE — Assurance expirée — {entreprise_name}', 'Bonjour {entreprise_name},\n\nVotre attestation d''assurance {type_assurance} a expiré le {date}.\n\n🔴 CONSÉQUENCE : Vos certificats de paiement sont BLOQUÉS jusqu''à régularisation.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,type_assurance,date,moe_name'),
('ASSUREUR_LISTE_NOIRE', 'alerte', 'BLOCAGE — Assureur non accepté — {entreprise_name}', 'Bonjour {entreprise_name},\n\nL''assureur {assureur_name} n''est pas accepté par NOMOΣ (assureur en LPS ou sans représentation en France).\n\n🔴 CONSÉQUENCE : Vos certificats sont BLOQUÉS.\n\nVeuillez fournir une attestation d''un assureur reconnu.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,assureur_name,moe_name'),
('PENALITE_APPLIQUEE', 'alerte', 'Pénalité appliquée — {montant} € — {lot_name}', 'Bonjour {entreprise_name},\n\nUne pénalité a été appliquée sur votre lot :\n\nMotif : {motif}\nRéférence CCAP : {reference}\nMontant : {montant} €\nType : {type}\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,montant,lot_name,motif,reference,type,moe_name'),
('SEUIL_PENALITE', 'alerte', 'ALERTE — Seuil pénalités critique — {entreprise_name}', 'Attention,\n\nLe cumul des pénalités pour {entreprise_name} (Lot {lot_name}) atteint {pourcentage}% du marché.\n\nSeuil critique : 5%\nCumul actuel : {montant} €\n\nCordialement,\nNOMOΣ', 'moe', 'entreprise_name,lot_name,pourcentage,montant'),
('CHANGEMENT_STATUT', 'alerte', 'Entreprise {entreprise_name} — Changement statut', 'Attention,\n\nUn changement de statut a été détecté pour {entreprise_name} :\n\nNouveau statut : {statut}\n\nVeuillez vérifier les implications sur l''opération.\n\nCordialement,\nNOMOΣ', 'moe', 'entreprise_name,statut'),
('RECAP_MENSUEL_PEDIGREE', 'alerte', 'Récapitulatif mensuel — Pedigrees à problème', 'Bonjour {moe_name},\n\nVoici le récapitulatif des Pedigrees nécessitant votre attention :\n\n{liste_problemes}\n\nCordialement,\nNOMOΣ', 'moe', 'moe_name,liste_problemes'),

-- Cloture (5 templates)
('APPEL_FONDS_PRORATA', 'cloture', 'Appel fonds compte prorata — {mois}', 'Bonjour {entreprise_name},\n\nL''appel de fonds du compte prorata pour {mois} est de {montant} €.\n\nCordialement,\n{gestionnaire}', 'entreprise', 'entreprise_name,mois,montant,gestionnaire'),
('ARBITRAGE_ENTREPRISE', 'cloture', 'Décision arbitrage — {objet}', 'Bonjour {entreprise_name},\n\nSuite à votre contestation, la décision suivante a été prise :\n\n{decision}\n\nCordialement,\n{moa_name}', 'entreprise', 'entreprise_name,objet,decision,moa_name'),
('DGD_SIGNATURE', 'cloture', 'DGD — Signature requise — {lot_name}', 'Bonjour {entreprise_name},\n\nLe Décompte Général Définitif pour votre lot est prêt.\n\nMontant DGD : {montant} €\n\nConnectez-vous à NOMOΣ pour vérifier et signer.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,lot_name,montant,moe_name'),
('CLOTURE_MARCHE', 'cloture', 'Clôture marché — {operation_name}', 'Bonjour,\n\nLe marché pour l''opération {operation_name} est officiellement clôturé.\n\nDate de clôture : {date}\n\nCordialement,\nNOMOΣ', 'all', 'operation_name,date'),
('BIENVENUE_ENTREPRISE', 'cloture', 'Bienvenue sur NOMOΣ — {operation_name}', 'Bonjour {entreprise_name},\n\nVous avez été ajouté à l''opération {operation_name}.\n\nLot : {lot_name}\nMontant marché : {montant} €\n\nConnectez-vous à NOMOΣ pour compléter votre Pedigree.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,operation_name,lot_name,montant,moe_name'),

-- Assurance (3 templates)
('ASSURANCE_J30', 'assurance', 'Assurance expire dans 30 jours — {entreprise_name}', 'Bonjour {entreprise_name},\n\nVotre {type_assurance} expire le {date}.\n\nMerci de renouveler et d''uploader la nouvelle attestation sur NOMOΣ.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,type_assurance,date,moe_name'),
('ASSURANCE_J7', 'assurance', 'URGENT — Assurance expire dans 7 jours — {entreprise_name}', '⚠️ Bonjour {entreprise_name},\n\nVotre {type_assurance} expire dans 7 JOURS ({date}).\n\nSans renouvellement, vos certificats seront BLOQUÉS.\n\nCordialement,\n{moe_name}', 'entreprise', 'entreprise_name,type_assurance,date,moe_name'),
('LIBERATION_RG', 'assurance', 'Libération retenue de garantie — {entreprise_name}', 'Bonjour,\n\nLa libération de la retenue de garantie pour {entreprise_name} (Lot {lot_name}) est prévue dans 30 jours.\n\nMontant RG : {montant} €\n\nCordialement,\nNOMOΣ', 'moe', 'entreprise_name,lot_name,montant');

-- Sample performance data
INSERT INTO performance_tracking (tenant_id, operation_id, situation_id, lot_id, date_depot, date_controle_opc, date_controle_moe, date_certificat, duree_opc_heures, duree_moe_heures, duree_totale_heures) VALUES
(1, 1, 1, 3, '2025-04-22 09:00:00', '2025-04-24 14:30:00', '2025-04-28 11:00:00', '2025-04-28 16:00:00', 53.5, 44.5, 151.0),
(1, 1, 2, 3, '2025-05-23 08:30:00', '2025-05-26 10:00:00', '2025-05-29 14:00:00', '2025-05-29 17:30:00', 73.5, 52.0, 153.0),
(1, 1, 3, 3, '2025-06-24 09:00:00', '2025-06-26 11:30:00', '2025-06-30 10:00:00', '2025-07-02 10:00:00', 50.5, 70.5, 193.0);
